// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using esii_2025_d1.Data;

#nullable disable

namespace esii2025d1.Entities
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250317160019_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("esii_2025_d1.Models.Jom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<float>("TestNumber")
                        .HasColumnType("real");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Joms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 3, 17, 16, 0, 19, 298, DateTimeKind.Utc).AddTicks(9785),
                            IsDone = false,
                            Label = "Joms",
                            TestNumber = 2.5f,
                            created_at = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(371),
                            updated_at = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(543)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(1002),
                            IsDone = true,
                            Label = "Joms2",
                            TestNumber = 7.5f,
                            created_at = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(1002),
                            updated_at = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(1003)
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(1008),
                            IsDone = true,
                            Label = "Joms3",
                            TestNumber = 10f,
                            created_at = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(1009),
                            updated_at = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(1009)
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(1013),
                            IsDone = false,
                            Label = "Joms4",
                            TestNumber = 62f,
                            created_at = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(1014),
                            updated_at = new DateTime(2025, 3, 17, 16, 0, 19, 299, DateTimeKind.Utc).AddTicks(1014)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
