// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using esii_2025_d1.Data;

#nullable disable

namespace esii2025d1.Entities
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250425133139_finishControllers")]
    partial class finishControllers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("esii_2025_d1.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("HourlyRate")
                        .HasColumnType("real");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7378),
                            Description = "Test assignment",
                            EndDate = new DateTime(2025, 5, 2, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7003),
                            HourlyRate = 20f,
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(6818),
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7589),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7947),
                            Description = "Test assignment2",
                            EndDate = new DateTime(2025, 5, 1, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7946),
                            HourlyRate = 20f,
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7945),
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7947),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7954),
                            Description = "Test assignment3",
                            EndDate = new DateTime(2025, 4, 28, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7953),
                            HourlyRate = 20f,
                            ProjectId = 2,
                            StartDate = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7953),
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(7954),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("esii_2025_d1.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(9673),
                            Email = "test@gmail.com",
                            Name = "Test Customer",
                            PhoneNumber = "123456789",
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 845, DateTimeKind.Utc).AddTicks(9833)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(154),
                            Email = "test2@gmail.com",
                            Name = "Test Customer2",
                            PhoneNumber = "923456789",
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(154)
                        });
                });

            modelBuilder.Entity("esii_2025_d1.Models.Jom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<float>("TestNumber")
                        .HasColumnType("real");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Joms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 4, 25, 13, 31, 38, 843, DateTimeKind.Utc).AddTicks(1774),
                            IsDone = false,
                            Label = "Joms",
                            TestNumber = 2.5f,
                            created_at = new DateTime(2025, 4, 25, 13, 31, 38, 843, DateTimeKind.Utc).AddTicks(2300),
                            updated_at = new DateTime(2025, 4, 25, 13, 31, 38, 843, DateTimeKind.Utc).AddTicks(2474)
                        });
                });

            modelBuilder.Entity("esii_2025_d1.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("entity_id")
                        .HasColumnType("integer");

                    b.Property<string>("entity_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("esii_2025_d1.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReportId");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(6614),
                            Name = "test",
                            Path = "test.jpg",
                            ProjectId = 1,
                            Type = "image",
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(6766)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(7073),
                            Name = "test2",
                            Path = "test2.jpg",
                            ProjectId = 2,
                            ReportId = 2,
                            Type = "Report",
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(7074)
                        });
                });

            modelBuilder.Entity("esii_2025_d1.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("esii_2025_d1.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("DailyWorkHours")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("HourlyRate")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(3032),
                            CustomerId = 1,
                            DailyWorkHours = 8,
                            Description = "Test project description",
                            HourlyRate = 14f,
                            Name = "Test Project",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(3174),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(3481),
                            CustomerId = 1,
                            DailyWorkHours = 4,
                            Description = "Test project description2",
                            HourlyRate = 16f,
                            Name = "Test Project2",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(3482),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(3485),
                            CustomerId = 1,
                            DailyWorkHours = 4,
                            Description = "Test project description3",
                            HourlyRate = 16f,
                            Name = "Test Project3",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(3486),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("esii_2025_d1.Models.ProjectUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InviterId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("esii_2025_d1.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(4648),
                            ProjectId = 1,
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(4797),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(5098),
                            ProjectId = 2,
                            UpdatedAt = new DateTime(2025, 4, 25, 13, 31, 38, 846, DateTimeKind.Utc).AddTicks(5099),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("esii_2025_d1.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("esii_2025_d1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyWorkHours")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("esii_2025_d1.Models.Assignment", b =>
                {
                    b.HasOne("esii_2025_d1.Models.Project", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("esii_2025_d1.Models.Media", b =>
                {
                    b.HasOne("esii_2025_d1.Models.Project", null)
                        .WithMany("Media")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("esii_2025_d1.Models.Report", null)
                        .WithMany("Media")
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("esii_2025_d1.Models.Project", b =>
                {
                    b.HasOne("esii_2025_d1.Models.Customer", null)
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("esii_2025_d1.Models.Report", b =>
                {
                    b.HasOne("esii_2025_d1.Models.Project", null)
                        .WithMany("Reports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("esii_2025_d1.Models.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("esii_2025_d1.Models.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Media");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("esii_2025_d1.Models.Report", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
