// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using esii_2025_d1.Data;

#nullable disable

namespace esii2025d1.Entities
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("esii_2025_d1.Models.Jom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<float?>("TestNumber")
                        .HasColumnType("real");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Joms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 3, 15, 19, 57, 8, 809, DateTimeKind.Utc).AddTicks(1754),
                            IsDone = false,
                            Label = "Joms",
                            TestNumber = 2.5f,
                            created_at = new DateTime(2025, 3, 15, 19, 57, 8, 809, DateTimeKind.Utc).AddTicks(2512),
                            updated_at = new DateTime(2025, 3, 15, 19, 57, 8, 809, DateTimeKind.Utc).AddTicks(2672)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 3, 15, 19, 57, 8, 809, DateTimeKind.Utc).AddTicks(3006),
                            IsDone = true,
                            Label = "Joms2",
                            TestNumber = 7.5f,
                            created_at = new DateTime(2025, 3, 15, 19, 57, 8, 809, DateTimeKind.Utc).AddTicks(3007),
                            updated_at = new DateTime(2025, 3, 15, 19, 57, 8, 809, DateTimeKind.Utc).AddTicks(3008)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
